import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ProgramCard } from "@/components/program-card";
import { getUniversity, programs, universities } from "@/lib/data";

export function generateStaticParams(){ return universities.map(u => ({slug:u.slug})); }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const u=getUniversity(slug);return {title:u?.shortName ?? "Вуз",description:u?.description};}
export default async function UniversityPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const university=getUniversity(slug);if(!university)notFound();const related=programs.filter(p=>p.universitySlug===slug);return <div className="detail-page"><section className="university-hero"><div className="container"><div className="breadcrumbs"><Link href="/universities">Вузы</Link><span>/</span>{university.shortName}</div><div className="university-hero-grid"><div className="university-logo large" style={{background:university.color}}>{university.shortName.slice(0,1)}</div><div><span className="overline">Государственный вуз · Москва</span><h1>{university.name}</h1><p>{university.description}</p><div className="hero-actions"><a className="button button-primary" href={university.website} target="_blank" rel="noreferrer">Официальный сайт ↗</a><button className="button outline-button">♡ В избранное</button></div></div></div></div></section><section className="section container"><div className="stats-band"><div><span>Программ</span><strong>{university.programsCount}</strong></div><div><span>Адрес</span><strong>{university.address}</strong></div><div><span>Данные обновлены</span><strong>29 июля 2026</strong></div></div><div className="section-head"><div><span className="overline">Направления</span><h2>Программы вуза</h2></div></div>{related.length?<div className="program-grid">{related.map(p=><ProgramCard key={p.id} program={p}/>)}</div>:<div className="empty-state"><b>Программы проходят проверку</b><p>Добавим их после подтверждения первоисточника.</p></div>}</section></div>}
